name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 도커 이미지 빌드 # (2)
      run: docker build -t jinu0125/kookbeefront .

    - name: Docker Hub 로그인 # (3)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Docker Hub 퍼블리시 # (4)
      run: docker push jinu0125/kookbeefront
    - name: hhh
      run: echo ${{ secrets.DOCKER_USERNAME }}
      
    - name: GCP 인스턴스 접속 및 애플리케이션 실행 # (5)
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_KEY }}
        port: ${{ secrets.GCP_SSH_PORT }}
        script: |
          sudo su
          sudo docker stop $(sudo docker ps -a | grep kookbeefront | awk '{print $1}') 
          sudo docker rm $(sudo docker ps -a | grep kookbeefront | awk '{print $1}') 
          sudo docker pull jinu0125/kookbeefront
          sudo docker run -d -p 3000:3000 --name kookbeefront jinu0125/kookbeefront
